{
    "nf_serving_size_qty": 8,
    "nf_serving_size_unit": "fl oz",
    "nf_saturated_fat": null,
    "allergen_contains_peanuts": null,
    "nf_vitamin_c_dv": 0,
    "nf_calories": 100,
    "nf_serving_weight_grams": null,
    "allergen_contains_gluten": null,
    "item_name": "Cola, Cherry",
    "allergen_contains_tree_nuts": null,
    "allergen_contains_soybeans": null,
    "nf_vitamin_a_dv": 0,
    "item_id": "51c3d78797c3e6d8d3b546cf",
    "old_api_id": null,
    "nf_calcium_dv": 0,
    "nf_refuse_pct": null,
    "nf_servings_per_container": 6,
    "brand_id": "51db3801176fe9790a89ae0b",
    "allergen_contains_eggs": null,
    "usda_fields": null,
    "nf_sodium": 25,
    "nf_calories_from_fat": 0,
    "allergen_contains_fish": null,
    "brand_name": "Coke",
    "item_description": "Cherry",
    "nf_total_fat": 0,
    "nf_iron_dv": 0,
    "nf_dietary_fiber": null,
    "nf_total_carbohydrate": 28,
    "nf_cholesterol": null,
    "allergen_contains_wheat": null,
    "leg_loc_id": 9999999,
    "updated_at": "2014-11-24T20:24:24.000Z",
    "nf_polyunsaturated_fat": null,
    "nf_monounsaturated_fat": null,
    "nf_protein": 0,
    "nf_trans_fatty_acid": null,
    "allergen_contains_shellfish": null,
    "nf_ingredient_statement": "Carbonated Water, High Fructose Corn Syrup and/or Sucrose, Caramel Color, Phosphoric Acid, Natural Flavors, Caffeine.",
    "allergen_contains_milk": null,
    "nf_water_grams": null,
    "nf_sugars": 28
}